production:
  adapter: postgresql
  database: dealers_revenge
  pool: 100

development:
  adapter: postgresql
  database: dealers_revenge
  host: localhost
  port: 5432

test: &test
  adapter: postgresql
  database: dealers_revenge
  host: localhost
  port: 5432

cucumber:
  <<: *test
