production:
  adapter: postgresql
  database: dealers_revenge
  pool: 100

development:
  adapter: postgresql
  database: dealers_revenge
  host: localhost
  port: 5432
#  username: postgres
#  password: isotope_bang

test: &test
  adapter: postgresql
  database: dealers_revenge
  host: localhost
  port: 5432
  #username: postgres
  #password: isotope_bang

cucumber:
  <<: *test
